### PR TITLE
Fix findRelated 

### LINKED ISSUE #691: 'Section.findRelated' 'findUpstream' vs 'findSideways'
The `nix.Section` method `findRelated` returns the first occurrence matching a filter criterion starting from any `Section` and returns it. To do this, it first searches downstream of the calling section, then upstream and then sideways.

The current implementation of `findUpstream` and `findSideways` are very similar. It looks like`findUpstream` already implements the "sideways" search. Maybe the `findUpstream` function could be refactored to speed up the upwards search or the "sideways" search was supposed to search sideways further down than it does currently.

### PR DESCRIPTION
**Pull request by jgrewe**
Due to our recent changes in findSection (exclude of the root section) the findRelated did not work properly in all cases (not caught by the tests :( ).
Extended the test cases and simplified findRelated, should fix #691

### CODE REVIEW

File: src/Section.cpp [hunk 1]
```diff
@@ -224,18 +222,18 @@ std::vector<Section> Section::findDownstream(const std::function<bool(Section)>
...
-        if (results.size() > 0) {
-            return results;
-        }
-        return p.findUpstream(filter);
+    if (p == none) {
+        return results;
+    }
+    if (filter(p)) {
+        results.push_back(p);
+        return results;
```
Comment (gicmo) [inline src/Section.cpp]: So we always return exactly one? Or am I am missing something? You wanna keep the result type as a vector to stay compatible with the other search functions?

Comment (jgrewe) [reply src/Section.cpp]: Yes, in this Case we return at maximum one section. And yes, I wanted to keep it similar to the other functions. Happy to change, if you want.
