### PR TITLE
fix max_depth pass through and extend tests

### LINKED ISSUE #689: 'File.findSections' missing 'max_depth' passthrough
Currently the `nix.File` method `findSections(max_depth)` in `File.hpp` does not seem to pass `max_depth` to the executing function which leads to an unlimited search result.

### PR DESCRIPTION
**Pull request by jgrewe**
fixes #689

### CODE REVIEW

File: src/File.cpp [hunk 1]
```diff
@@ -1,3 +1,4 @@
+
```
Comment (gicmo) [inline src/File.cpp]: Accident new newline?

Comment (jgrewe) [reply src/File.cpp]: ups

Comment (jgrewe) [reply src/File.cpp]: cf #695
